#!/usr/bin/python3
import os
import py_compile

# Get the Python file name from the environment variable
pyfile = os.getenv('PYFILE')

# Check if the PYFILE environment variable is set
if pyfile:
    # Compile the Python file
    py_compile.compile(pyfile, cfile=pyfile + 'c')
else:
    print("Error: PYFILE environment variable is not set.")
    exit(1)
